### ISSUE TITLE
SPJS cannot close COM port

### ISSUE THREAD

**Issue by oscarhc** [johnlauer/serial-port-json-server#17]
Hi,

   Opened browser with local SPJS on Win 7 and Server 2008; in both tried some commands. After opening port, sent the close command and get this error:

WIN7-  {"Error" : "We could not find the serial port COM1 that you were trying to close."}
2008 - {"Error" : "We could not find the serial port COM5 that you were trying to close."}

   The only way to close the port is shutting down SPJS. Any ideas?

   TIA, Oscar.

**Comment by ril3y** [comment]
How are you opening it?  Are you writing your own ui to talk to is or are
you using chilipeppr and seeing these errors on the server?  Sorry as I am
a bit confused here.  Can you provide us with more information?

**Comment by oscarhc** [comment]
Hello Ril3y,  
    
   I'm talking to the server directly from the browser as localhost:8989

   Just recorded a video for you to see what is happening. Have tried with real and virtual COM ports with same result. Check the [video] (https://Pegasus.tinytake.com/sf/MTI2ODk1XzgxNjU2Mw)

   I would like to build a UI in C# for it, but first need to understand how it works. 

   TIA, Oscar.

**Comment by johnlauer** [comment]
Oscar,

My first take is it appears you are not successfully connecting to your serial port even though SPJS is seemingly getting a success in the video. When you connect, most serial ports will send some kind of hello message but I don't see anything. Of course it's possible your serial port doesn't send anything, but it just feels weird that you're using 2400 baud. Can you try sending some content to the serial port to see what comes back?

Anyway, there's also 1 anomaly to be aware of, which is that when you close a serial port, it's only really the next character that you send that creates the official closing of the port. This is not ideal, but it was a fix provided by one of the contributors to get the Mac to close the port and some versions of Linux. It made the Windows implementation then have the same characteristic. What I would suggest is that if you are doing C# which means you're only using Windows then you should perhaps abstract out the close method to something like serialportclose_windows.go and/or tweak the code in your own fork to make the close be more direct on Windows. I've been wanting to fix that close sequence for a long time since I don't like that the Mac caused a change that made Windows work less nicely. Of course it would be nice to get a perfect port close on all platforms and I do think that's possible if somebody debugs the close process a bit more. It's worth it given the amount of folks now using SPJS.

Also, I would use the http://chilipeppr.com/serialport URL to test out SPJS instead of the built-in webserver version because it's 10x more advanced of an interface.

-John

**Comment by johnlauer** [comment]
The latest version fixes the close problem. I am now seeing consistent port closing on all platforms.

**Comment by JimF42** [comment]
@johnlauer I have also noticed an anomaly with closing a port also. In this case if I send "close COM3**\n**" it does not work:
> {"Error" : "We could not find the serial port COM3 that you were trying to write to."}

But, If I don't have the final newline or if I have a space after the COM port number and before the newline ("close COM3 **\n**"), it also works fine.

**Comment by johnlauer** [comment]
@JimF42 fix checked in a few hours ago. Good catch.

**Comment by JimF42** [comment]
@johnlauer, thanks for the fix. Do you have an ETA as to when will it be available as a complied version?

**Comment by johnlauer** [comment]
Getting close. Maybe within days.

**Comment by johnlauer** [comment]
@JimF42 You can go ahead and try out the latest build at http://chilipeppr.com/downloads/v1.82/

**Comment by JimF42** [comment]
@johnlauer Thanks. Sorry, I didn't mean for you to rush it out--I was just wondering what time frame you had in mind. I will try it this evening.

**Comment by JimF42** [comment]
@johnlauer Yup, close now works with an ending newline.
